spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      open-in-view: false

  datasource:
    url: jdbc:mysql://prod-db:3306/myapp_prod
    username: prod_user
    password: prod_pass

server:
  port: 9090

logging:
  config: classpath:logback-prod.xml