spring:
  profiles:
    active: dev   # default profile (can be overridden at runtime)

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver



  mvc:
    servlet:
      path: /api

  server:
    port: 8080  # default, overridden in profiles if needed

